### ISSUE TITLE
NameError: name 'args' is not defined

### ISSUE THREAD

**Issue by loneyao** [xinufo/airtest-runner#2]
Ran 0 tests in 0.013s

FAILED (errors=1)

Failure
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/suite.py", line 163, in _handleClassSetUp
    setUpClass()
  File "/Users/mac/Downloads/airtest-runner-master/runner.py", line 20, in setUpClass
    cls.args = args
NameError: name 'args' is not defined

**Comment by xinufo** [comment]
The 'args' is a global variable, and it is declared [here](https://github.com/xinufo/airtest-runner/blob/66e49f0ecaf854ae6ba92e6ff9fafe5ab0e3bd5b/runner.py#L117).
Run with the command below should be ok
```shell
# run test
python runner.py YOUR_SCRIPT_DIR

# generate a report
python report.py YOUR_LOG_DIR
```
